/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.jpl7.Query;
import org.jpl7.Term;

/**
 *
 * @author Carolina Botina
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        
        
    }
    
    String Item="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        padres_de = new javax.swing.JRadioButton();
        tios_de = new javax.swing.JRadioButton();
        primos_de = new javax.swing.JRadioButton();
        ancestros_de = new javax.swing.JRadioButton();
        btn_consultar = new javax.swing.JButton();
        integrantes = new javax.swing.JComboBox<>();
        imagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel1.setText("Selecciona la opción seguido del integrante a consultar:");

        consultas.add(padres_de);
        padres_de.setText("Padres de");
        padres_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padres_deActionPerformed(evt);
            }
        });

        consultas.add(tios_de);
        tios_de.setText("Tios de");
        tios_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tios_deActionPerformed(evt);
            }
        });

        consultas.add(primos_de);
        primos_de.setText("Primos de");

        consultas.add(ancestros_de);
        ancestros_de.setText("Ancestros de");

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        integrantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "florelia", "marina", "nelly", "diego", "aida", "johana", "carlos", "fredy", "flor", "max", "stiven", "aimet", "javier", "andres", "didimo", "juan_jose", "stella", "juis_jr", "diana", "hernan", "danilo", "yuli", "janeth", "german", "mauricio", "sigifredo", "sebastian", "carol", "mario", "aracelly", "flor", "abraham", "luis_galves", "ester", "fidelia", "adam", "maria", "reinaldo", "fidelina_pumalpa", "rafael", "carlina", "alvaro", "fidelina", "tatarabuelo_david", "tatarabuela_david", "tatarabuelo_cordoba", "tatarabuela_cordoba", "tatarabuelo_villota", "tatarabuela_villota", "tatarabuelo_rosero", "tatarabuela_rosero", "tatarabuelo_pumalpa", "tatarabuela_pumalpa", "tatarabuelo_galves", "tatarabuela_galves", "tatarabuelo_munoz", "tatarabuela_munoz", "tatarabuelo_rosero2", "tatarabuela_rosero2" }));
        integrantes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                integrantesItemStateChanged(evt);
            }
        });
        integrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integrantesActionPerformed(evt);
            }
        });

        imagen.setText("jLabel2");

        texto.setEditable(false);
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        texto.setRows(5);
        texto.setBorder(null);
        texto.setMaximumSize(new java.awt.Dimension(500, 100));
        jScrollPane1.setViewportView(texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primos_de)
                                    .addComponent(tios_de)
                                    .addComponent(padres_de)
                                    .addComponent(ancestros_de))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(integrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_consultar)
                        .addGap(183, 183, 183))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_consultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(padres_de)
                                .addGap(18, 18, 18)
                                .addComponent(tios_de)
                                .addGap(18, 18, 18)
                                .addComponent(primos_de)
                                .addGap(18, 18, 18)
                                .addComponent(ancestros_de)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(integrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void padres_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padres_deActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_padres_deActionPerformed

    private void integrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integrantesActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_integrantesActionPerformed

    private void integrantesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_integrantesItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_integrantesItemStateChanged

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        Item = integrantes.getSelectedItem().toString();
        //JOptionPane.showMessageDialog(null,"El item es:"+Item);
        String consulta="";
        texto.setText("");
        if(padres_de.isSelected())
        {
            //System.out.println("wasaaaaa");
            consulta="padres_de(X,"+Item+")";
            
        }
        else if(tios_de.isSelected())
        {
            consulta="tio_de(X,"+Item+")";
            
        }
        else if(primos_de.isSelected())
        {
            consulta="primo_de(X,"+Item+")";
        }
        else if(ancestros_de.isSelected())
        {
            consulta="ancestro_de(X,"+Item+")";
        }
        
        if(padres_de.isSelected() || tios_de.isSelected() || primos_de.isSelected() || ancestros_de.isSelected())
        {
            
            consultar(consulta);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Elija consulta");
        }
        
            
        
    }//GEN-LAST:event_btn_consultarActionPerformed
    private void consultar(String consulta)
    {
           Query con=new Query(consulta);
           //LinkedList<String> d=new LinkedList<>();
           
           
           if(con.hasSolution())
           {    
               
               for (Map<String, Term> map : con) {
                   String datos=map.get("X").toString();
                   //d.add(datos);
                   //arreglo.add(datos);
                   texto.setText(texto.getText()+"\n"+datos);
                  
               }
               
               
               
           }
           
          
           
    }
    private void tios_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tios_deActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tios_deActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ancestros_de;
    private javax.swing.JButton btn_consultar;
    private javax.swing.ButtonGroup consultas;
    private javax.swing.JLabel imagen;
    private javax.swing.JComboBox<String> integrantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton padres_de;
    private javax.swing.JRadioButton primos_de;
    private javax.swing.JTextArea texto;
    private javax.swing.JRadioButton tios_de;
    // End of variables declaration//GEN-END:variables
}
